FROM golang:1.18 as builder

ENV GOPROXY=https://goproxy.cn,direct

WORKDIR /workspace

# Copy the go source
COPY . .

RUN go mod download

# Build
RUN CGO_ENABLED=0 go build -a -o bin/apiserver cmd/apiserver/main.go
RUN CGO_ENABLED=0 go build -a -o bin/controller-manager cmd/manager/main.go

FROM alpine:3.16

COPY --from=builder /workspace/bin/apiserver .
COPY --from=builder /workspace/bin/controller-manager .

RUN apk update
RUN apk add ca-certificates
