---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-iass-controller
  namespace: default
  labels:
    api: k8s-iass
    controller: "true"
spec:
  selector:
    matchLabels:
      api: k8s-iass
      controller: "true"
  replicas: 1
  template:
    metadata:
      labels:
        api: k8s-iass
        controller: "true"
    spec:
      containers:
      - name: controller
        image: 2030047311/k8s-iaas:0.0.1
        command:
        - "./controller-manager"
        args:
        resources:
          requests:
            cpu: 100m
            memory: 200Mi
          limits:
            cpu: 100m
            memory: 300Mi
      volumes:
      - name: apiserver-certs
        secret:
          secretName: k8s-iass
